package com.kamsiob.kamai

import android.content.pm.PackageManager
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.google.common.truth.Truth.assertThat
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Guards the strongest claims in the privacy policy at the level of the built
 * package, not the source.
 *
 * The policy says Kam AI touches the network only when asked, collects nothing,
 * and has no analytics. Those are checkable properties of the APK, and a
 * dependency added six months from now can quietly break them without anybody
 * editing the manifest by hand. This test is what makes that fail loudly.
 */
@RunWith(AndroidJUnit4::class)
class PrivacyClaimsTest {

    private val context = InstrumentationRegistry.getInstrumentation().targetContext

    private fun requestedPermissions(): List<String> {
        val info = context.packageManager.getPackageInfo(
            context.packageName,
            PackageManager.GET_PERMISSIONS,
        )
        return info.requestedPermissions?.toList().orEmpty()
    }

    /**
     * Permissions that end up on the installed package without the app asking
     * for them, and which grant it nothing it did not already have.
     *
     * `DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` is generated by AndroidX and
     * is a signature-level permission on the app's own receivers.
     *
     * `ACCESS_LOCAL_NETWORK` is injected by the platform from Android 16
     * onward for any app that holds INTERNET but has not opted into the new
     * local-network model. It is not in either of Kam AI's merged manifests,
     * which were checked directly; the platform adds it at install time. It is
     * listed here rather than filtered blindly so that the day it stops being
     * platform noise, this test starts failing again.
     */
    private val platformInjected = setOf(
        "android.permission.ACCESS_LOCAL_NETWORK",
    )

    @Test
    fun theAppShipsWithExactlyOneRealPermission() {
        // INTERNET is the only permission any feature needs: downloading a
        // model, a voice, or a pack, and opt-in web search. Anything else
        // appearing here is a dependency smuggling in capability the app does
        // not use and the privacy policy does not describe.
        val permissions = requestedPermissions()
            .filterNot { it.endsWith("DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION") }
            .filterNot { it in platformInjected }

        assertThat(permissions).containsExactly("android.permission.INTERNET")
    }

    @Test
    fun nothingCanStartTheAppInTheBackground() {
        val permissions = requestedPermissions()

        // WorkManager pulled all three of these in while being entirely unused.
        // An app that only touches the network when asked has no business
        // starting itself at boot or holding a wake lock.
        assertThat(permissions).doesNotContain("android.permission.RECEIVE_BOOT_COMPLETED")
        assertThat(permissions).doesNotContain("android.permission.WAKE_LOCK")
        assertThat(permissions).doesNotContain("android.permission.FOREGROUND_SERVICE")
    }

    @Test
    fun thereIsNoAdvertisingIdPermission() {
        assertThat(requestedPermissions())
            .doesNotContain("com.google.android.gms.permission.AD_ID")
    }

    @Test
    fun theAppOptsOutOfCloudBackup() {
        // The user moves their data with Settings, Backup and restore, which
        // writes a file they choose where to put. Nothing goes to Google.
        val info = context.packageManager.getApplicationInfo(context.packageName, 0)
        val allowsBackup = (info.flags and android.content.pm.ApplicationInfo.FLAG_ALLOW_BACKUP) != 0
        assertThat(allowsBackup).isFalse()
    }

    @Test
    fun theApplicationIdIsTheOneDeclaredToPlay() {
        assertThat(context.packageName).isEqualTo("com.kamsiob.kamai")
    }
}
