package com.kamsiob.kamai

import android.content.pm.PackageManager
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.google.common.truth.Truth.assertThat
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Guards the strongest claims in the privacy policy at the level of the built
 * package, not the source.
 *
 * The policy says Kam AI touches the network only when asked, collects nothing,
 * and has no analytics. Those are checkable properties of the APK, and a
 * dependency added six months from now can quietly break them without anybody
 * editing the manifest by hand. This test is what makes that fail loudly.
 */
@RunWith(AndroidJUnit4::class)
class PrivacyClaimsTest {

    private val context = InstrumentationRegistry.getInstrumentation().targetContext

    private fun requestedPermissions(): List<String> {
        val info = context.packageManager.getPackageInfo(
            context.packageName,
            PackageManager.GET_PERMISSIONS,
        )
        return info.requestedPermissions?.toList().orEmpty()
    }

    /**
     * Permissions that end up on the installed package without the app asking
     * for them, and which grant it nothing it did not already have.
     *
     * `DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` is generated by AndroidX and
     * is a signature-level permission on the app's own receivers.
     *
     * `ACCESS_LOCAL_NETWORK` is injected by the platform from Android 16
     * onward for any app that holds INTERNET but has not opted into the new
     * local-network model. It is not in either of Kam AI's merged manifests,
     * which were checked directly; the platform adds it at install time. It is
     * listed here rather than filtered blindly so that the day it stops being
     * platform noise, this test starts failing again.
     */
    private val platformInjected = setOf(
        "android.permission.ACCESS_LOCAL_NETWORK",
    )

    /**
     * Every permission the app asks for, and why it has it.
     *
     * This used to assert exactly INTERNET, which stopped being true when
     * background downloads and voice typing were built, and nobody noticed
     * because the instrumented tests are not part of the ordinary loop. A test
     * asserting something false is worse than no test: whoever eventually runs
     * it reads a real failure as a stale one and stops trusting the file.
     *
     * The point survives the change. The list is exhaustive and each entry is
     * justified, so anything *else* appearing here is a dependency smuggling in
     * capability the app does not use and the privacy policy does not describe,
     * which is what this test exists to catch.
     */
    private val justified = mapOf(
        // Downloading a model, a voice or a content pack, and opt-in web search.
        "android.permission.INTERNET" to "downloads and opt-in web search",
        // Read-only, and only about the current connection: whether there is one
        // and whether it is metered, so a five gigabyte model never starts on
        // cellular without the user choosing it (#79).
        "android.permission.ACCESS_NETWORK_STATE" to "is there a connection, is it metered",
        // A model download runs for twenty minutes and must survive the app being
        // backgrounded, which needs a foreground service and its notification.
        "android.permission.FOREGROUND_SERVICE" to "downloads continue in the background",
        "android.permission.FOREGROUND_SERVICE_DATA_SYNC" to "the type that service declares",
        "android.permission.POST_NOTIFICATIONS" to "download progress, and nothing else",
        // Voice typing, transcribed on device. Asked for at first use, and the
        // microphone is not required to install.
        "android.permission.RECORD_AUDIO" to "voice typing, transcribed on device",
    )

    @Test
    fun everyPermissionOnThePackageIsOneWeChose() {
        val permissions = requestedPermissions()
            .filterNot { it.endsWith("DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION") }
            .filterNot { it in platformInjected }

        assertThat(permissions).containsExactlyElementsIn(justified.keys)
    }

    @Test
    fun nothingCanStartTheAppInTheBackground() {
        val permissions = requestedPermissions()

        // WorkManager pulled these in while being entirely unused. An app that
        // only touches the network when asked has no business starting itself at
        // boot or holding a wake lock.
        assertThat(permissions).doesNotContain("android.permission.RECEIVE_BOOT_COMPLETED")
        assertThat(permissions).doesNotContain("android.permission.WAKE_LOCK")

        // FOREGROUND_SERVICE was on this list and has been taken off it
        // deliberately. It is now held, for downloads that continue while the app
        // is in the background, which is a service the *user* started and can see
        // in a notification. That is a different thing from the app waking itself
        // up, which is what this test is about and which is still forbidden by
        // the two assertions above.
    }

    @Test
    fun thereIsNoAdvertisingIdPermission() {
        assertThat(requestedPermissions())
            .doesNotContain("com.google.android.gms.permission.AD_ID")
    }

    @Test
    fun theAppOptsOutOfCloudBackup() {
        // The user moves their data with Settings, Backup and restore, which
        // writes a file they choose where to put. Nothing goes to Google.
        val info = context.packageManager.getApplicationInfo(context.packageName, 0)
        val allowsBackup = (info.flags and android.content.pm.ApplicationInfo.FLAG_ALLOW_BACKUP) != 0
        assertThat(allowsBackup).isFalse()
    }

    @Test
    fun theApplicationIdIsTheOneDeclaredToPlay() {
        assertThat(context.packageName).isEqualTo("com.kamsiob.kamai")
    }
}
